### ISSUE TITLE
User profile does not handle 404 when fetching room

### ISSUE THREAD

**Issue by speedyman09** [LittleBigRefresh/refresh-web#17]
Due to a recent change in Refresh, viewing any user's page on the website will present a 404 error:

https://github.com/LittleBigRefresh/Refresh/assets/17880243/4ff6822a-5886-4061-8492-1b96679e7f3d

**Comment by speedyman09** [comment]
nitpick: errors should stay anchored onto the viewport and cover more area
![image](https://github.com/LittleBigRefresh/refresh-web/assets/17880243/8a56b309-09ce-46c0-b36f-7663b3b1a65b)

**Comment by jvyden** [comment]
Disagree, makes them easier to read on wide monitors

**Comment by sudokoko** [comment]
Issue here is that the page is attempting to fetch the room for the user - but since the user is offline it can't be found therefore a 404 is returned.

**Comment by speedyman09** [comment]
I guess it’s an easy fix, just check if the user is offline and if they are, then don’t attempt to fetch their room

**Comment by sudokoko** [comment]
Or, could just suppress the message if this is the case. Not sure which one would be preferred tho

**Comment by jvyden** [comment]
The room is how online/offline status is fetched. Just suppress the message.
