### ISSUE TITLE
Cache page results

### ISSUE THREAD

**Issue by turecross321** [LittleBigRefresh/refresh-web#44]
This would mean that it would be possible to store the scroll position between navigation and thus make for a substantially better browsing experience

**Comment by jvyden** [comment]
Is this possible to do without sacrificing the already suffering code quality? I'm not well-versed in Angular so this is probably better done by someone who knows what they're doing.

**Comment by turecross321** [comment]
I'm not too well-versed in Angular either, but is usually done with a CacheService from what I've gathered. You could look at what I've done with soundshapes-web, but that code is admittedly somewhat unreadable. 

As far as keeping the scroll position goes, it's just a routing setting.

**Comment by jvyden** [comment]
No longer happening as `refresh-web` is feature locked.
