### ISSUE TITLE
E-mail verification doesn't use tooltip component

### ISSUE THREAD

**Issue by turecross321** [LittleBigRefresh/refresh-web#48]
![image](https://github.com/LittleBigRefresh/refresh-web/assets/51852312/01071740-0027-48f0-a608-7fb0ff0c8497)

**Comment by speedyman09** [comment]
Thats just an aria label tho

**Comment by jvyden** [comment]
Nope, this is a bug. It's taking `title=` on the notification literally because everything and your mother is a reserved type/keyword and HTML and JS
