### ISSUE TITLE
rightSideRouterLinks is an empty array on user update

### ISSUE THREAD

**Issue by speedyman08** [LittleBigRefresh/refresh-web#51]
Currently, if you attempt to change any user settings (themes, auth), the usual buttons that allow you to access settings get hidden:
![image](https://github.com/LittleBigRefresh/refresh-web/assets/17880243/c859f691-2e35-449e-9a15-e1c1353cd53b)

When user settings are updated, the "authService.onUserUpdate" method is executed. This is picked up by the "userWatcher" event.
![image](https://github.com/LittleBigRefresh/refresh-web/assets/17880243/7c40390b-60a4-464e-8ca9-0e37263e6bd8)

In app.component.ts, the "userWatcher" event is checked for changes, if there are changes, the "handleUserUpdate" method is executed. this.rightSideRouterLinks is set to an empty array. 
![image](https://github.com/LittleBigRefresh/refresh-web/assets/17880243/6a6fa684-f790-450e-b99c-aecdbf6af181)

For some reason, this.login is undefined at this point and the "this.rightSideRouterLinks.push" commands are not executed because of that. This causes the buttons to disappear.

Video:

https://github.com/LittleBigRefresh/refresh-web/assets/17880243/c46922ad-e964-4e6e-9e2f-b4bd569b8a86

**Comment by speedyman09** [comment]
should this issue be closed? it was related to the previous version of the project

**Comment by jvyden** [comment]
Not until rewrite is done, I think
