### ISSUE TITLE
Store API access tokens in cookies instead of local storage

### ISSUE THREAD

**Issue by speedyman09** [LittleBigRefresh/refresh-web#55]
Tokens should <ins>never</ins> be stored in localStorage. That just opens up XSS vulnerabilities. Instead, tokens should be stored in Http-Only cookies. They are inaccessible by local Javascript scripts and ideally, the browser would automatically include these cookies in http request headers. That is what makes them more secure.

**Comment by jvyden** [comment]
I don't really see how cookies are more secure.

> That just opens up XSS vulnerabilities.
We don't really do anything weird about how we use Angular. If you're able to break out of Angular's safety checks then that's a much much bigger problem.

> They are inaccessible by local Javascript scripts
This is just ...wrong? You can access them via `console.log(document.cookie)`.

Additionally, many other programs such as Discord and I believe Element store their tokens in `localStorage` and get away with it. I guess it would be more secure if we moved APIv3 to a separate subdomain to help with same-origin policy but that just complicates the already messy frontend.
